type: app
description: Default stackfile usecase description
# template used to create the project
template: ulha-angular-stack/default-architecture-template
inputs:
  some_input: value
# list of plugins to be applied after project creation
plugins:
  - plugin: ulha-angular-stack/angular-ngrx-store-plugin
    inputs:
      some_input: value
      some_list:
        - item1
        - item2
